### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [k-kinzal/oh-my-zsh-sinon-theme#2]
Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by k-kinzal** [comment]
@unixorn 
https://github.com/k-kinzal/oh-my-zsh-sinon-theme/blob/master/LICENSE
added LICENSE.

**Comment by unixorn** [comment]
thanks! I'm trying to clean up the awesome-zsh-plugins list so that everything in it has a license
